/**
 * TMD DOMINICANA — OFFICIAL TECHNICAL PDF SPEC SHEETS & MANUFACTURER BROCHURES
 * Autogenerated mapping connecting all 40 machines to local verified PDF documents
 */

export interface MachinePdfMapping {
  machineId: string;
  brand: string;
  modelCode: string;
  fichaPdfUrl: string;
  fichaFileName: string;
  brochurePdfUrl: string;
  brochureFileName: string;
}

export interface OfficialBrochure {
  id: string;
  title: string;
  brand: string;
  fileName: string;
  fileUrl: string;
  sizeMb: number;
  category: string;
}

export const MACHINE_PDFS_MAP: Record<string, MachinePdfMapping> = {
  'jcb-3cx-eco': {
    machineId: 'jcb-3cx-eco',
    brand: 'JCB',
    modelCode: '3CX',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_3CX-14.pdf',
    fichaFileName: 'FT_JCB_3CX-14.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    brochureFileName: 'JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf'
  },
  'jcb-3cx-compact': {
    machineId: 'jcb-3cx-compact',
    brand: 'JCB',
    modelCode: '3CX Compact',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_3CX_Compact.pdf',
    fichaFileName: 'FT_JCB_3CX_Compact.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    brochureFileName: 'JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf'
  },
  'jcb-3cx-14': {
    machineId: 'jcb-3cx-14',
    brand: 'JCB',
    modelCode: '3CX-14',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_3CX-14.pdf',
    fichaFileName: 'FT_JCB_3CX-14.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    brochureFileName: 'JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf'
  },
  'jcb-1cxt': {
    machineId: 'jcb-1cxt',
    brand: 'JCB',
    modelCode: '1CXT',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_1CXT.pdf',
    fichaFileName: 'FT_JCB_1CXT.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    brochureFileName: 'JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf'
  },
  'jcb-215t': {
    machineId: 'jcb-215t',
    brand: 'JCB',
    modelCode: '215T',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_215T.pdf',
    fichaFileName: 'FT_JCB_215T.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    brochureFileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf'
  },
  'jcb-250t': {
    machineId: 'jcb-250t',
    brand: 'JCB',
    modelCode: '250T',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_250T.pdf',
    fichaFileName: 'FT_JCB_250T.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    brochureFileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf'
  },
  'jcb-270t': {
    machineId: 'jcb-270t',
    brand: 'JCB',
    modelCode: '270T',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_270T.pdf',
    fichaFileName: 'FT_JCB_270T.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    brochureFileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf'
  },
  'jcb-3ts-8t-teleskid': {
    machineId: 'jcb-3ts-8t-teleskid',
    brand: 'JCB',
    modelCode: '3TS-8T',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_100C-2.pdf',
    fichaFileName: 'FT_JCB_100C-2.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    brochureFileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf'
  },
  'jcb-215-skid': {
    machineId: 'jcb-215-skid',
    brand: 'JCB',
    modelCode: '215',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_215.pdf',
    fichaFileName: 'FT_JCB_215.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    brochureFileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf'
  },
  'jcb-270-skid': {
    machineId: 'jcb-270-skid',
    brand: 'JCB',
    modelCode: '270',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_270.pdf',
    fichaFileName: 'FT_JCB_270.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    brochureFileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf'
  },
  'jcb-220x-excavator': {
    machineId: 'jcb-220x-excavator',
    brand: 'JCB',
    modelCode: '220X',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_220X.pdf',
    fichaFileName: 'FT_JCB_220X.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_220X_Official_Brochure.pdf',
    brochureFileName: 'JCB_220X_Official_Brochure.pdf'
  },
  'jcb-150x-excavator': {
    machineId: 'jcb-150x-excavator',
    brand: 'JCB',
    modelCode: '150X',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_150X.pdf',
    fichaFileName: 'FT_JCB_150X.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_220X_Official_Brochure.pdf',
    brochureFileName: 'JCB_220X_Official_Brochure.pdf'
  },
  'jcb-370x-excavator': {
    machineId: 'jcb-370x-excavator',
    brand: 'JCB',
    modelCode: '370X',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_370X.pdf',
    fichaFileName: 'FT_JCB_370X.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_220X_Official_Brochure.pdf',
    brochureFileName: 'JCB_220X_Official_Brochure.pdf'
  },
  'jcb-18z-1': {
    machineId: 'jcb-18z-1',
    brand: 'JCB',
    modelCode: '18Z-1',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_100C-2.pdf',
    fichaFileName: 'FT_JCB_100C-2.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Mini_Excavators_48Z_51R_55Z_57C_Brochure.pdf',
    brochureFileName: 'JCB_Mini_Excavators_48Z_51R_55Z_57C_Brochure.pdf'
  },
  'jcb-50z-1': {
    machineId: 'jcb-50z-1',
    brand: 'JCB',
    modelCode: '50Z-1',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_100C-2.pdf',
    fichaFileName: 'FT_JCB_100C-2.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Mini_Excavators_48Z_51R_55Z_57C_Brochure.pdf',
    brochureFileName: 'JCB_Mini_Excavators_48Z_51R_55Z_57C_Brochure.pdf'
  },
  'jcb-540-170-loadall': {
    machineId: 'jcb-540-170-loadall',
    brand: 'JCB',
    modelCode: '540-170',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_100C-2.pdf',
    fichaFileName: 'FT_JCB_100C-2.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Loadall_531_70.pdf',
    brochureFileName: 'JCB_Loadall_531_70.pdf'
  },
  'jcb-427-wheel-loader': {
    machineId: 'jcb-427-wheel-loader',
    brand: 'JCB',
    modelCode: '427',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_JCB_427.pdf',
    fichaFileName: 'FT_JCB_427.pdf',
    brochurePdfUrl: '/assets/brochures/JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    brochureFileName: 'JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf'
  },
  'liugong-835t': {
    machineId: 'liugong-835t',
    brand: 'LiuGong',
    modelCode: '835T',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LiuGong_835T.pdf',
    fichaFileName: 'FT_LiuGong_835T.pdf',
    brochurePdfUrl: '/assets/brochures/LiuGong_856H.pdf',
    brochureFileName: 'LiuGong_856H.pdf'
  },
  'liugong-856t': {
    machineId: 'liugong-856t',
    brand: 'LiuGong',
    modelCode: '856T',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LiuGong_856T.pdf',
    fichaFileName: 'FT_LiuGong_856T.pdf',
    brochurePdfUrl: '/assets/brochures/LiuGong_856H.pdf',
    brochureFileName: 'LiuGong_856H.pdf'
  },
  'liugong-922e': {
    machineId: 'liugong-922e',
    brand: 'LiuGong',
    modelCode: '922E',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LiuGong_922E.pdf',
    fichaFileName: 'FT_LiuGong_922E.pdf',
    brochurePdfUrl: '/assets/brochures/LiuGong_922E_Official_Brochure.pdf',
    brochureFileName: 'LiuGong_922E_Official_Brochure.pdf'
  },
  'liugong-925e': {
    machineId: 'liugong-925e',
    brand: 'LiuGong',
    modelCode: '925E',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LiuGong_925E.pdf',
    fichaFileName: 'FT_LiuGong_925E.pdf',
    brochurePdfUrl: '/assets/brochures/LiuGong_922E_Official_Brochure.pdf',
    brochureFileName: 'LiuGong_922E_Official_Brochure.pdf'
  },
  'liugong-4180d': {
    machineId: 'liugong-4180d',
    brand: 'LiuGong',
    modelCode: '4180D',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LiuGong_4180D.pdf',
    fichaFileName: 'FT_LiuGong_4180D.pdf',
    brochurePdfUrl: '/assets/brochures/LiuGong_4180D_Motor_Grader_Official_Brochure.pdf',
    brochureFileName: 'LiuGong_4180D_Motor_Grader_Official_Brochure.pdf'
  },
  'liugong-b160cl': {
    machineId: 'liugong-b160cl',
    brand: 'LiuGong',
    modelCode: 'B160CL',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LiuGong_B160CL.pdf',
    fichaFileName: 'FT_LiuGong_B160CL.pdf',
    brochurePdfUrl: '/assets/brochures/LiuGong_922E_Official_Brochure.pdf',
    brochureFileName: 'LiuGong_922E_Official_Brochure.pdf'
  },
  'kubota-bx23s': {
    machineId: 'kubota-bx23s',
    brand: 'Kubota',
    modelCode: 'BX23S',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Kubota_BX23S.pdf',
    fichaFileName: 'FT_Kubota_BX23S.pdf',
    brochurePdfUrl: '/assets/brochures/Kubota_Full_Product_Line_Catalog_2025.pdf',
    brochureFileName: 'Kubota_Full_Product_Line_Catalog_2025.pdf'
  },
  'kubota-l4701': {
    machineId: 'kubota-l4701',
    brand: 'Kubota',
    modelCode: 'L4701',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Kubota_L4701.pdf',
    fichaFileName: 'FT_Kubota_L4701.pdf',
    brochurePdfUrl: '/assets/brochures/Kubota_Standard_L_Series_L3301_L3901_L4701_Brochure.pdf',
    brochureFileName: 'Kubota_Standard_L_Series_L3301_L3901_L4701_Brochure.pdf'
  },
  'kubota-m5-091': {
    machineId: 'kubota-m5-091',
    brand: 'Kubota',
    modelCode: 'M5-091',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Kubota_BX1880.pdf',
    fichaFileName: 'FT_Kubota_BX1880.pdf',
    brochurePdfUrl: '/assets/brochures/Kubota_Full_Product_Line_Catalog_2025.pdf',
    brochureFileName: 'Kubota_Full_Product_Line_Catalog_2025.pdf'
  },
  'kubota-kx033-4': {
    machineId: 'kubota-kx033-4',
    brand: 'Kubota',
    modelCode: 'KX033-4',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Kubota_BX1880.pdf',
    fichaFileName: 'FT_Kubota_BX1880.pdf',
    brochurePdfUrl: '/assets/brochures/Kubota_KX040_5_Compact_Excavator_Brochure.pdf',
    brochureFileName: 'Kubota_KX040_5_Compact_Excavator_Brochure.pdf'
  },
  'kubota-svl75-2s': {
    machineId: 'kubota-svl75-2s',
    brand: 'Kubota',
    modelCode: 'SVL75-2S',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Kubota_BX1880.pdf',
    fichaFileName: 'FT_Kubota_BX1880.pdf',
    brochurePdfUrl: '/assets/brochures/Kubota_SVL75_3_Compact_Track_Loader_Brochure.pdf',
    brochureFileName: 'Kubota_SVL75_3_Compact_Track_Loader_Brochure.pdf'
  },
  'ls-mt225s': {
    machineId: 'ls-mt225s',
    brand: 'LS Tractor',
    modelCode: 'MT225S',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LS_Tractor_MT225S.pdf',
    fichaFileName: 'FT_LS_Tractor_MT225S.pdf',
    brochurePdfUrl: '/assets/brochures/LS_Tractor_MT2_Official_Brochure.pdf',
    brochureFileName: 'LS_Tractor_MT2_Official_Brochure.pdf'
  },
  'ls-mt240e': {
    machineId: 'ls-mt240e',
    brand: 'LS Tractor',
    modelCode: 'MT240E',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LS_Tractor_MT240E.pdf',
    fichaFileName: 'FT_LS_Tractor_MT240E.pdf',
    brochurePdfUrl: '/assets/brochures/LS_Tractor_MT2_Official_Brochure.pdf',
    brochureFileName: 'LS_Tractor_MT2_Official_Brochure.pdf'
  },
  'ls-mt573cps': {
    machineId: 'ls-mt573cps',
    brand: 'LS Tractor',
    modelCode: 'MT573CPS',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_LS_Tractor_MT573CPS.pdf',
    fichaFileName: 'FT_LS_Tractor_MT573CPS.pdf',
    brochurePdfUrl: '/assets/brochures/LS_Tractor_MT4_Official_Brochure.pdf',
    brochureFileName: 'LS_Tractor_MT4_Official_Brochure.pdf'
  },
  'yanmar-yt235': {
    machineId: 'yanmar-yt235',
    brand: 'Yanmar',
    modelCode: 'YT235',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Yanmar_YT235.pdf',
    fichaFileName: 'FT_Yanmar_YT235.pdf',
    brochurePdfUrl: '/assets/brochures/Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf',
    brochureFileName: 'Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf'
  },
  'yanmar-yt359': {
    machineId: 'yanmar-yt359',
    brand: 'Yanmar',
    modelCode: 'YT359',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Yanmar_YT359.pdf',
    fichaFileName: 'FT_Yanmar_YT359.pdf',
    brochurePdfUrl: '/assets/brochures/Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf',
    brochureFileName: 'Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf'
  },
  'yanmar-ag600': {
    machineId: 'yanmar-ag600',
    brand: 'Yanmar',
    modelCode: 'AG600',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Yanmar_AG600.pdf',
    fichaFileName: 'FT_Yanmar_AG600.pdf',
    brochurePdfUrl: '/assets/brochures/Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf',
    brochureFileName: 'Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf'
  },
  'ammann-ars70': {
    machineId: 'ammann-ars70',
    brand: 'Ammann',
    modelCode: 'ARS 70',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Ammann_ARS_70.pdf',
    fichaFileName: 'FT_Ammann_ARS_70.pdf',
    brochurePdfUrl: '/assets/brochures/Ammann_ARS_110_Compactor_Spec.pdf',
    brochureFileName: 'Ammann_ARS_110_Compactor_Spec.pdf'
  },
  'ammann-arx26': {
    machineId: 'ammann-arx26',
    brand: 'Ammann',
    modelCode: 'ARX 26',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Ammann_ARX_26.pdf',
    fichaFileName: 'FT_Ammann_ARX_26.pdf',
    brochurePdfUrl: '/assets/brochures/Ammann_ARX_Tandem_Vibratory_Rollers_Brochure.pdf',
    brochureFileName: 'Ammann_ARX_Tandem_Vibratory_Rollers_Brochure.pdf'
  },
  'ammann-apf30-65': {
    machineId: 'ammann-apf30-65',
    brand: 'Ammann',
    modelCode: 'APF 30/65',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_Ammann_APF_30_65.pdf',
    fichaFileName: 'FT_Ammann_APF_30_65.pdf',
    brochurePdfUrl: '/assets/brochures/Ammann_Light_Compaction_Rammers_Plates_Brochure.pdf',
    brochureFileName: 'Ammann_Light_Compaction_Rammers_Plates_Brochure.pdf'
  },
  'imer-mcbp30': {
    machineId: 'imer-mcbp30',
    brand: 'IMER',
    modelCode: 'MCBP 30',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_IMER_Group_MCBP_30.pdf',
    fichaFileName: 'FT_IMER_Group_MCBP_30.pdf',
    brochurePdfUrl: '/assets/brochures/IMER_Syntesi_190_350_Technical_Manual.pdf',
    brochureFileName: 'IMER_Syntesi_190_350_Technical_Manual.pdf'
  },
  'imer-mc1200': {
    machineId: 'imer-mc1200',
    brand: 'IMER',
    modelCode: 'MC 1200',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_IMER_Group_MC_1200.pdf',
    fichaFileName: 'FT_IMER_Group_MC_1200.pdf',
    brochurePdfUrl: '/assets/brochures/IMER_Syntesi_190_350_Technical_Manual.pdf',
    brochureFileName: 'IMER_Syntesi_190_350_Technical_Manual.pdf'
  },
  'afex-midex': {
    machineId: 'afex-midex',
    brand: 'AFEX',
    modelCode: 'AFEX-MIDEX-18KG',
    fichaPdfUrl: '/assets/fichas_tecnicas/FT_AFEX_AFEX_Mid_Excavator_System.pdf',
    fichaFileName: 'FT_AFEX_AFEX_Mid_Excavator_System.pdf',
    brochurePdfUrl: '/assets/brochures/AFEX_Heavy_Equipment_Fire_Systems_Spec.pdf',
    brochureFileName: 'AFEX_Heavy_Equipment_Fire_Systems_Spec.pdf'
  },
};

export const ALL_OFFICIAL_BROCHURES: OfficialBrochure[] = [
  {
    id: 'brochure-1',
    title: 'AFEX Heavy Equipment Fire Systems Spec',
    brand: 'AFEX',
    fileName: 'AFEX_Heavy_Equipment_Fire_Systems_Spec.pdf',
    fileUrl: '/assets/brochures/AFEX_Heavy_Equipment_Fire_Systems_Spec.pdf',
    sizeMb: 2.74,
    category: 'Seguridad Contra Incendios'
  },
  {
    id: 'brochure-2',
    title: 'Ammann ARS 110 Compactor Spec',
    brand: 'Ammann',
    fileName: 'Ammann_ARS_110_Compactor_Spec.pdf',
    fileUrl: '/assets/brochures/Ammann_ARS_110_Compactor_Spec.pdf',
    sizeMb: 0.81,
    category: 'Compactación'
  },
  {
    id: 'brochure-3',
    title: 'Ammann ARX Tandem Vibratory Rollers Brochure',
    brand: 'Ammann',
    fileName: 'Ammann_ARX_Tandem_Vibratory_Rollers_Brochure.pdf',
    fileUrl: '/assets/brochures/Ammann_ARX_Tandem_Vibratory_Rollers_Brochure.pdf',
    sizeMb: 0.85,
    category: 'Compactación'
  },
  {
    id: 'brochure-4',
    title: 'Ammann Light Compaction Rammers Plates Brochure',
    brand: 'Ammann',
    fileName: 'Ammann_Light_Compaction_Rammers_Plates_Brochure.pdf',
    fileUrl: '/assets/brochures/Ammann_Light_Compaction_Rammers_Plates_Brochure.pdf',
    sizeMb: 7.16,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-5',
    title: 'Ammann Soil and Asphalt Compactors Master Range',
    brand: 'Ammann',
    fileName: 'Ammann_Soil_and_Asphalt_Compactors_Master_Range.pdf',
    fileUrl: '/assets/brochures/Ammann_Soil_and_Asphalt_Compactors_Master_Range.pdf',
    sizeMb: 15.68,
    category: 'Compactación'
  },
  {
    id: 'brochure-6',
    title: 'Cummins QSB Industrial Diesel Engines Brochure',
    brand: 'Cummins',
    fileName: 'Cummins_QSB_Industrial_Diesel_Engines_Brochure.pdf',
    fileUrl: '/assets/brochures/Cummins_QSB_Industrial_Diesel_Engines_Brochure.pdf',
    sizeMb: 2.30,
    category: 'Energía & Motores'
  },
  {
    id: 'brochure-7',
    title: 'Cummins Q Range Commercial Generators Brochure',
    brand: 'Cummins',
    fileName: 'Cummins_Q_Range_Commercial_Generators_Brochure.pdf',
    fileUrl: '/assets/brochures/Cummins_Q_Range_Commercial_Generators_Brochure.pdf',
    sizeMb: 4.49,
    category: 'Energía & Motores'
  },
  {
    id: 'brochure-8',
    title: 'IMER Syntesi 190 350 Technical Manual',
    brand: 'IMER Group',
    fileName: 'IMER_Syntesi_190_350_Technical_Manual.pdf',
    fileUrl: '/assets/brochures/IMER_Syntesi_190_350_Technical_Manual.pdf',
    sizeMb: 1.55,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-9',
    title: 'IMER Syntesi 350 Exploded Parts Catalog',
    brand: 'IMER Group',
    fileName: 'IMER_Syntesi_350_Exploded_Parts_Catalog.pdf',
    fileUrl: '/assets/brochures/IMER_Syntesi_350_Exploded_Parts_Catalog.pdf',
    sizeMb: 3.26,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-10',
    title: 'JCB 220X Official Brochure',
    brand: 'JCB',
    fileName: 'JCB_220X_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_220X_Official_Brochure.pdf',
    sizeMb: 1.91,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-11',
    title: 'JCB 3CX Pothole Master Brochure',
    brand: 'JCB',
    fileName: 'JCB_3CX_Pothole_Master_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_3CX_Pothole_Master_Brochure.pdf',
    sizeMb: 2.73,
    category: 'Retroexcavadoras'
  },
  {
    id: 'brochure-12',
    title: 'JCB Backhoe Loader 3CX 4CX Range Brochure',
    brand: 'JCB',
    fileName: 'JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Backhoe_Loader_3CX_4CX_Range_Brochure.pdf',
    sizeMb: 5.95,
    category: 'Retroexcavadoras'
  },
  {
    id: 'brochure-13',
    title: 'JCB Compact Excavators 25Z 26C Brochure',
    brand: 'JCB',
    fileName: 'JCB_Compact_Excavators_25Z_26C_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Compact_Excavators_25Z_26C_Brochure.pdf',
    sizeMb: 1.52,
    category: 'Excavación'
  },
  {
    id: 'brochure-14',
    title: 'JCB Fastrac',
    brand: 'JCB',
    fileName: 'JCB_Fastrac.pdf',
    fileUrl: '/assets/brochures/JCB_Fastrac.pdf',
    sizeMb: 1.98,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-15',
    title: 'JCB Loadall 531 70',
    brand: 'JCB',
    fileName: 'JCB_Loadall_531_70.pdf',
    fileUrl: '/assets/brochures/JCB_Loadall_531_70.pdf',
    sizeMb: 0.26,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-16',
    title: 'JCB Mini Excavators 48Z 51R 55Z 57C Brochure',
    brand: 'JCB',
    fileName: 'JCB_Mini_Excavators_48Z_51R_55Z_57C_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Mini_Excavators_48Z_51R_55Z_57C_Brochure.pdf',
    sizeMb: 2.56,
    category: 'Excavación'
  },
  {
    id: 'brochure-17',
    title: 'JCB Site Dumpers 1T to 9T Fleet Brochure',
    brand: 'JCB',
    fileName: 'JCB_Site_Dumpers_1T_to_9T_Fleet_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Site_Dumpers_1T_to_9T_Fleet_Brochure.pdf',
    sizeMb: 3.88,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-18',
    title: 'JCB Skid Steer 135 330 Heavy Series Specs',
    brand: 'JCB',
    fileName: 'JCB_Skid_Steer_135_330_Heavy_Series_Specs.pdf',
    fileUrl: '/assets/brochures/JCB_Skid_Steer_135_330_Heavy_Series_Specs.pdf',
    sizeMb: 1.55,
    category: 'Cargadores Compactos'
  },
  {
    id: 'brochure-19',
    title: 'JCB Skid Steer and Track Loader Fleet Brochure',
    brand: 'JCB',
    fileName: 'JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Skid_Steer_and_Track_Loader_Fleet_Brochure.pdf',
    sizeMb: 0.88,
    category: 'Cargadores Compactos'
  },
  {
    id: 'brochure-20',
    title: 'JCB Teletruk Logistics Brochure',
    brand: 'JCB',
    fileName: 'JCB_Teletruk_Logistics_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Teletruk_Logistics_Brochure.pdf',
    sizeMb: 3.35,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-21',
    title: 'JCB Teletruk Wastemaster Brochure',
    brand: 'JCB',
    fileName: 'JCB_Teletruk_Wastemaster_Brochure.pdf',
    fileUrl: '/assets/brochures/JCB_Teletruk_Wastemaster_Brochure.pdf',
    sizeMb: 4.85,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-22',
    title: 'Kubota Full Product Line Catalog 2025',
    brand: 'Kubota',
    fileName: 'Kubota_Full_Product_Line_Catalog_2025.pdf',
    fileUrl: '/assets/brochures/Kubota_Full_Product_Line_Catalog_2025.pdf',
    sizeMb: 8.10,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-23',
    title: 'Kubota KX040 5 Compact Excavator Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_KX040_5_Compact_Excavator_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_KX040_5_Compact_Excavator_Brochure.pdf',
    sizeMb: 2.68,
    category: 'Excavación'
  },
  {
    id: 'brochure-24',
    title: 'Kubota L02 Series Tractor Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_L02_Series_Tractor_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_L02_Series_Tractor_Brochure.pdf',
    sizeMb: 19.15,
    category: 'Agrícola & Movimiento'
  },
  {
    id: 'brochure-25',
    title: 'Kubota L3901 Technical Specs',
    brand: 'Kubota',
    fileName: 'Kubota_L3901_Technical_Specs.pdf',
    fileUrl: '/assets/brochures/Kubota_L3901_Technical_Specs.pdf',
    sizeMb: 1.42,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-26',
    title: 'Kubota M7 4 Heavy Agriculture Tractor Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_M7_4_Heavy_Agriculture_Tractor_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_M7_4_Heavy_Agriculture_Tractor_Brochure.pdf',
    sizeMb: 2.08,
    category: 'Agrícola & Movimiento'
  },
  {
    id: 'brochure-27',
    title: 'Kubota RTV520 Midsize Utility Vehicle Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_RTV520_Midsize_Utility_Vehicle_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_RTV520_Midsize_Utility_Vehicle_Brochure.pdf',
    sizeMb: 3.05,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-28',
    title: 'Kubota Standard L Series L3301 L3901 L4701 Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_Standard_L_Series_L3301_L3901_L4701_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_Standard_L_Series_L3301_L3901_L4701_Brochure.pdf',
    sizeMb: 3.28,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-29',
    title: 'Kubota SVL65 2S Compact Track Loader Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_SVL65_2S_Compact_Track_Loader_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_SVL65_2S_Compact_Track_Loader_Brochure.pdf',
    sizeMb: 25.72,
    category: 'Cargadores Compactos'
  },
  {
    id: 'brochure-30',
    title: 'Kubota SVL75 3 Compact Track Loader Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_SVL75_3_Compact_Track_Loader_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_SVL75_3_Compact_Track_Loader_Brochure.pdf',
    sizeMb: 32.93,
    category: 'Cargadores Compactos'
  },
  {
    id: 'brochure-31',
    title: 'Kubota SVL97 3 Heavy Track Loader Brochure',
    brand: 'Kubota',
    fileName: 'Kubota_SVL97_3_Heavy_Track_Loader_Brochure.pdf',
    fileUrl: '/assets/brochures/Kubota_SVL97_3_Heavy_Track_Loader_Brochure.pdf',
    sizeMb: 34.95,
    category: 'Cargadores Compactos'
  },
  {
    id: 'brochure-32',
    title: 'LiuGong 4180D Motor Grader Official Brochure',
    brand: 'LiuGong',
    fileName: 'LiuGong_4180D_Motor_Grader_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/LiuGong_4180D_Motor_Grader_Official_Brochure.pdf',
    sizeMb: 0.94,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-33',
    title: 'LiuGong 856H',
    brand: 'LiuGong',
    fileName: 'LiuGong_856H.pdf',
    fileUrl: '/assets/brochures/LiuGong_856H.pdf',
    sizeMb: 2.87,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-34',
    title: 'LiuGong 922E Official Brochure',
    brand: 'LiuGong',
    fileName: 'LiuGong_922E_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/LiuGong_922E_Official_Brochure.pdf',
    sizeMb: 3.18,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-35',
    title: 'LiuGong 936E Heavy Excavator Official Brochure',
    brand: 'LiuGong',
    fileName: 'LiuGong_936E_Heavy_Excavator_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/LiuGong_936E_Heavy_Excavator_Official_Brochure.pdf',
    sizeMb: 1.27,
    category: 'Excavación'
  },
  {
    id: 'brochure-36',
    title: 'LS Tractor MT1 Official Brochure',
    brand: 'LS Tractor',
    fileName: 'LS_Tractor_MT1_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/LS_Tractor_MT1_Official_Brochure.pdf',
    sizeMb: 1.11,
    category: 'Agrícola & Movimiento'
  },
  {
    id: 'brochure-37',
    title: 'LS Tractor MT2 Official Brochure',
    brand: 'LS Tractor',
    fileName: 'LS_Tractor_MT2_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/LS_Tractor_MT2_Official_Brochure.pdf',
    sizeMb: 0.77,
    category: 'Agrícola & Movimiento'
  },
  {
    id: 'brochure-38',
    title: 'LS Tractor MT3 Series Brochure',
    brand: 'LS Tractor',
    fileName: 'LS_Tractor_MT3_Series_Brochure.pdf',
    fileUrl: '/assets/brochures/LS_Tractor_MT3_Series_Brochure.pdf',
    sizeMb: 5.39,
    category: 'Agrícola & Movimiento'
  },
  {
    id: 'brochure-39',
    title: 'LS Tractor MT4 Official Brochure',
    brand: 'LS Tractor',
    fileName: 'LS_Tractor_MT4_Official_Brochure.pdf',
    fileUrl: '/assets/brochures/LS_Tractor_MT4_Official_Brochure.pdf',
    sizeMb: 10.56,
    category: 'Agrícola & Movimiento'
  },
  {
    id: 'brochure-40',
    title: 'TMD Dominicana Catalogo Maestro Oficial 2026',
    brand: 'TMD Dominicana',
    fileName: 'TMD_Dominicana_Catalogo_Maestro_Oficial_2026.pdf',
    fileUrl: '/assets/brochures/TMD_Dominicana_Catalogo_Maestro_Oficial_2026.pdf',
    sizeMb: 3.84,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-41',
    title: 'TMD Master Catalogo Oficial 2026',
    brand: 'TMD Dominicana',
    fileName: 'TMD_Master_Catalogo_Oficial_2026.pdf',
    fileUrl: '/assets/brochures/TMD_Master_Catalogo_Oficial_2026.pdf',
    sizeMb: 3.84,
    category: 'Catálogo General'
  },
  {
    id: 'brochure-42',
    title: 'Yanmar ViO Mini Excavator Series Brochure',
    brand: 'Yanmar',
    fileName: 'Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf',
    fileUrl: '/assets/brochures/Yanmar_ViO_Mini_Excavator_Series_Brochure.pdf',
    sizeMb: 2.61,
    category: 'Excavación'
  },
];

export const getMachinePdfUrls = (machineId: string): MachinePdfMapping | null => {
  return MACHINE_PDFS_MAP[machineId] || null;
};